expname: Venturi_220906_3
data:
  path: '/gpfs/exfel/exp/SPB/202122/p002948/scratch/machine-learning/FFC/Data/Venturi'
  train: ['FFC_Venturi_run_60.h5','FFC_Venturi_run_61.h5']
  test: ['FFC_Venturi_run_60.h5']
  pad_size: [256, 512]

training:
  dir: Results
  lr_g: 0.0002
  lr_d: 0.0001
  lr_decay_factor: 0.1
  lr_decay_epochs: 150
  num_epochs: 500
  batch_size: 180
  lambda_mse: 1000
  lambda_G: 1
  lambda_fsc: 0
  print_loss_freq_iter: 20
  save_plot_freq_epoch: 1
  save_model_freq_epoch: 20
